# Generated by Django 6.1.1 on 2026-09-07 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('destination_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=60)),
                ('iata_code', models.CharField(blank=True, default='', help_text='Primary airport code, e.g. FLR. Blank if the city has no airport.', max_length=3)),
                ('timezone', models.CharField(default='UTC', max_length=40)),
                ('avg_daily_cost_usd', models.DecimalField(decimal_places=2, default=0, help_text='Rough per-person daily spend, used to sanity-check trip budgets.', max_digits=7)),
            ],
            options={
                'ordering': ['country', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'country'), name='uniq_destination_name_per_country')],
            },
        ),
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('traveler_id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=60)),
                ('bio', models.CharField(blank=True, default='', max_length=200)),
                ('is_domain_verified', models.BooleanField(default=False, help_text='True when the account email is on a verified .edu / company domain.')),
                ('joined_on', models.DateField(auto_now_add=True)),
                ('home_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='trips.destination')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='traveler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('message', models.CharField(blank=True, default='', max_length=300)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='trips.traveler')),
            ],
            options={
                'ordering': ['-requested_at', 'requester'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget_min_usd', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('budget_max_usd', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('group_size', models.PositiveSmallIntegerField(default=1)),
                ('seats_open', models.PositiveSmallIntegerField(default=0, help_text='How many companions the poster will still accept. 0 = closed.')),
                ('visibility', models.CharField(choices=[('private', 'Private (only me)'), ('public', 'Public (open to join requests)')], default='private', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('completed', 'Completed')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('companions', models.ManyToManyField(blank=True, related_name='joined_trips', through='trips.JoinRequest', to='trips.traveler')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trips.traveler')),
            ],
            options={
                'ordering': ['start_date', 'title'],
            },
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='trips.trip'),
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('stop_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField(help_text='1-based order of this city within the route.')),
                ('nights', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stops', to='trips.destination')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'ordering': ['trip', 'position'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('transport', 'Transport'), ('hotel', 'Hotel / stay'), ('activity', 'Place or activity'), ('food', 'Food'), ('rental', 'Rental')], max_length=12)),
                ('title', models.CharField(max_length=120)),
                ('day_number', models.PositiveSmallIntegerField(help_text='Which day of the whole trip this falls on (day 1 = departure day).')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('booking_url', models.URLField(blank=True, default='')),
                ('booking_status', models.CharField(choices=[('not_booked', 'Not booked'), ('partial', 'Partially booked'), ('booked', 'Booked')], default='not_booked', max_length=12)),
                ('is_hidden_gem', models.BooleanField(default=False)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trips.tripstop')),
            ],
            options={
                'ordering': ['day_number', 'start_time', 'item_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(fields=('owner', 'title', 'start_date'), name='uniq_trip_title_per_owner_per_start'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='trip_end_date_after_start_date'),
        ),
        migrations.AddConstraint(
            model_name='joinrequest',
            constraint=models.UniqueConstraint(fields=('trip', 'requester'), name='uniq_join_request_per_trip_per_traveler'),
        ),
        migrations.AddConstraint(
            model_name='tripstop',
            constraint=models.UniqueConstraint(fields=('trip', 'position'), name='uniq_stop_position_per_trip'),
        ),
        migrations.AddConstraint(
            model_name='tripstop',
            constraint=models.UniqueConstraint(fields=('trip', 'destination'), name='uniq_destination_per_trip'),
        ),
        migrations.AddConstraint(
            model_name='itineraryitem',
            constraint=models.UniqueConstraint(fields=('stop', 'day_number', 'title'), name='uniq_item_per_stop_per_day'),
        ),
    ]
